steps:
  - name: ":rspec:"
    #command: gem install rspec && bundle exec rspec --color specs
    command: bundle install && rspec app/specs
    plugins:
     - docker#v5.9.0:
        image: ruby:3.2
        workdir: /app
        mount-checkout: false
        volumes:
          - ./app:/app