env:
  FOO: bar
steps:
  - name: ":rspec:"
    command: gem install rspec && rspec --init && rspec --color specs
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2
          workdir: /app
  - label: ":pipeline: upload"
    command: "buildkite-agent pipeline upload .buildkite/pipeline2.yml"
    env:
      TARGET_ENV: "staging"
  - name: "group ${FOO}"
    steps:
    - commands: echo hello 