
steps:
  - label: ":rspec:"  
    command: 
      - bundle config set --local with 'test'
      - ls -al
      # - bundle install
      #- gem install rspec && rspec --color spec
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2
          workdir: /app 
  