steps:
  - name: ":rspec:"
    #command: gem install rspec && bundle exec rspec --color specs
    #command: bundle install && rspec app/specs
    command: gem install rspec && rspec --init && rspec --color specs
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2
          workdir: /app