steps:
  - name: ":rspec:"
    command: gem install rspec && ls -al
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2  
  - label: ":hammer: Testing"
    command: gem install rubocop && ls -al
    plugins:
      - docker#v5.7.0:
          image: ruby:3.2           