steps:
  - name: ":rspec:"
    command: gem install rspec && rspec --color spec
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2  
  - label: ":hammer: workdir check"
    command: ls -al
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2
          workdir: /workdir/app           