steps:
  - name: ":rspec:"
    command: gem install rspec && rspec --color spec
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2  
  - label: ":hammer: workdir check"
    command: ls -al && rspec
    plugins:
      - docker#v5.9.0:
          image: meltwater/rspec:3.8        