
steps:
  - label: ":rspec:"  
    command: 
      - bundle config set --local with 'test'
      - cd app && bundle install
      - rspec --color spec
      - rubocop --auto-gen-config
    plugins:
      # - artifacts#v1.9.2:
      #    upload: ".rubocop*.yml"
      - git-clean#v1.0.0:
          flags: "-fdqx"
      - docker#v5.9.0:
          image: ruby:3.2
          workdir: /app 
  