steps:
  - name: ":rspec:"
    #command: gem install rspec && bundle exec rspec --color specs
    command: pwd && ls -al
    plugins:
     - docker#v5.7.0:
        image: ruby:3.2
        workdir: /app
        run: app