
steps:
  - label: ":rspec:"  
    command: 
      - bundle config set --local with 'test'
      - cd app && bundle install
      - rspec --color spec
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2
          workdir: /app 
  